### ISSUE TITLE
Cross-platform?

### ISSUE THREAD

**Issue by adamski** [abaga129/FilmstripMaker#2]
I see this is Windows-only (by the `Windows.h` include)
Would be great to have this as a cross-platform utility (OS X & Linux too). 
Thanks for sharing anyhow.

**Comment by abaga129** [comment]
Thanks. I'll take a look into it and see about making it cross-platform. I should be able to get it setup to test on Linux, but I don't have access to an OS X machine.

**Comment by adamski** [comment]
You could look at the juce command-line app template. 
I'd be happy to test on OS X too.

**Comment by abaga129** [comment]
That would be awesome if you could test in on OS X. I went ahead and took the windows specific parts out so everything should compile fine on OS X and Linux now. I'm trying to get opencv set up on my Linux machine to test it.

**Comment by abaga129** [comment]
It builds on Linux for me so OS X shouldn't be a problem!
